//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CusReg
    {
        public int UserID { get; set; }
        public string CustomerName { get; set; }
        public int CustomerID { get; set; }
        public string Email { get; set; }
        public string Location { get; set; }
        public Nullable<int> MobileNO { get; set; }
        public string Newspaper { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
    }
}
