//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vreg
    {
        public int UesID { get; set; }
        public string VendorName { get; set; }
        public int VendorID { get; set; }
        public string Newspaper { get; set; }
        public Nullable<decimal> Cost_Per_Month { get; set; }
    }
}
